### PR TITLE
Add input callback

### LINKED ISSUE #31: Add example to README of rich content in rank_list
It took me a little while to understand enough to build a (silly) example, so I think it would be worthwhile showing how to build rich content inside of a rank_list! (Probably with a more interesting example)

```
library(shiny)
library(sortable)

ui <- fluidPage(

    titlePanel("Old Faithful Geyser Data"),

    fluidRow(
        bucket_list(
            header = "Hello",
            add_rank_list(
                text = "List 1",
                input_id = "list_1",
                labels = c(
                    list(tags$div(tags$b("Hi"), tags$br(), tags$b("Two"))), 
                    "Hello"
                    )
            ),
            add_rank_list(
                text = "List 2",
                input_id = "list_2",
                labels = NULL
            ),
            add_rank_list(
                text = "List 3",
                input_id = "list_3",
                labels = c("two")
            ),
            add_rank_list(
                text = "List 4",
                input_id = "list_4",
                labels = c("three")
            )
        )
    ),
    fluidRow(textOutput("presentation"))
)

server <- function(input, output) {
  output$presentation <- renderText(
      capture.output(str(input$list_1))
  )
}

shinyApp(ui = ui, server = server)
```

However, I will say that the Shiny input does not seem to be initialized properly at the start (requires moving something to get the inputs working), and it would be nice to have some hooks into what is returned. I.e. if I could define my own ID for each label and have that returned.

image

After moving something:
```
chr [1:2] "Hi \nTwo\n" "Hello"
```

(I believe this is because of the following, which does not fire until sorted:)
https://github.com/rstudio/sortable/blob/ef56c4c0ae2a7eef4063132c83f3a0f257abe568/R/rank_list.R#L81

However, if you want a "hidden" ID or something, you _can_ use `font-size: 0` as a trick 😄 

```
add_rank_list(
                text = "List 1",
                input_id = "list_1",
                labels = c(
                    list(tags$div(tags$span(id = "test", "test", style = "font-size: 0"), tags$b("Hi"), tags$br(), tags$b("Two"))), 
                    "Hello"
                    )
            )

# results in:
chr [1:2] "test Hi \nTwo\n" "Hello"
```

### PR DESCRIPTION
**Pull request by colearendt**
Make callback configurable
Add example application with configurable callback and rich content
Close #31

### CODE REVIEW

**Comment by colearendt** [comment]
Oops. Looks like this will need to be re-added back on top once #28 lands 😅

**Comment by colearendt** [comment]
Rebased on top of #28 . You can change the target to go into that PR if you expect it to live a bit longer.

**Comment by schloerke** [comment]
@colearendt What about looking for an `id` of the child and if no id exists, it returns the text?

**Comment by colearendt** [comment]
The weird thing is that the id of the child is often meaningless (we define that element). It’s the id of the grandchild that might be interesting.

**Comment by schloerke** [comment]
So there's two things at play here.

1. I don't want to allow people to have their own callback.  Instead I'd rather look for an `id` or return the inner text.
2. Currently we have a default div that contains the whole child.  Should remove that if the item being supplied is an htmltag? (vs a character value)
  * This would allow the direct setting of values without an item container div
  * Then we'd only need the child's id value.

@colearendt , Does this sound ok?

**Comment by colearendt** [comment]
Ahh yes, that makes sense. And yeah, I think that'd be pretty awesome - would that work for sortable.js? I thought the class was important on that outer div to tell sortable.js that this is an "item" for the list. Would you set that class on the user's provided object?

**Comment by schloerke** [comment]
It should work.  Mind if I take this PR over?

**Comment by colearendt** [comment]
Not at all! Please do 😄

**Pull request closed without merging**
